workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "cx-dev"'
      variables:
        TAG: $CI_COMMIT_SHORT_SHA
    - if: '$CI_COMMIT_TAG =~ /^RC-.*/ || $CI_COMMIT_TAG =~ /^v.*/'
      variables:
        TAG: $CI_COMMIT_TAG
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG:  $CI_COMMIT_SHORT_SHA  
stages:
  - build
build:
  tags:
    - shell
  stage:  build
  script:  
    - export VERS=$(cat "./ui/.nvmrc")

    - docker login $HARBOR_REGISTRY -u $HARBOR_REGISTRY_USERNAME -p $HARBOR_REGISTRY_PASSWORD 2>/dev/null
    - docker build -f Dockerfile-cx -t $HARBOR_REGISTRY/cx-mon/observ-ui-perses:$TAG --build-arg NODE_VERS=${VERS:1} .
    - docker push -a $HARBOR_REGISTRY/cx-mon/observ-ui-perses
  rules:
    - if: '$CI_COMMIT_TAG =~ /^RC-.*/ || $CI_COMMIT_TAG =~ /^v.*/ || $CI_COMMIT_BRANCH == "cx-dev"'
    - when: never
