FROM docker.cldx.io/golang:1.23.4-bookworm  AS build-env
ARG NODE_VER=20.14.0
ENV GOPROXY=http://prx-1.int.ops.cldx.ru:3000
RUN apt update && apt install -y mailcap wget make yq
RUN mkdir /perses
RUN mkdir /plugins

RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash; \
    . ~/.bashrc && nvm install $NODE_VER
COPY . .
RUN . ~/.bashrc && make build-ui \
    # удаляем из целей install-default-plugins - потому что там захардкожено 
    # скачиваение плагинов из репозитория perses на github
    # и заменяем на 
    && sed -i 's/generate: assets-compress install-default-plugins/generate: assets-compress/g' Makefile
RUN cd scripts/plugin && ./install_plugins.sh
RUN make build-api
RUN make build-cli


FROM hbr-1.int.ops.cldx.ru/cx-os/cx-os:base

USER nobody
COPY --from=build-env --chown=nobody:nobody                  /perses /perses
COPY --from=build-env --chown=nobody:nobody /go/bin/perses       /bin/
COPY --from=build-env --chown=nobody:nobody /go/bin/percli       /bin/
COPY --chown=nobody:nobody LICENSE                           /LICENSE
COPY --chown=nobody:nobody cue/schemas/                      /etc/perses/cue/schemas/
COPY --chown=nobody:nobody cue.mod/                          /etc/perses/cue.mod/
COPY --chown=nobody:nobody docs/examples/config.docker.yaml  /etc/perses/config.yaml
COPY --from=build-env --chown=nobody:nobody                  /plugins        /etc/perses/plugins
COPY --from=build-env --chown=nobody:nobody                  /go/plugins-archive/   /etc/perses/plugins-archive/
COPY --from=build-env --chown=nobody:nobody                  /etc/mime.types /etc/mime.types
WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
