FROM docker.cldx.io/golang:1.23-bookworm  AS build-env
ARG NODE_VER=20.14.0
RUN apt update && apt install -y mailcap wget make
RUN mkdir /perses
RUN wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash; \
    . ~/.bashrc && nvm install $NODE_VER
COPY . .
RUN . ~/.bashrc && make build

FROM hbr-1.int.ops.cldx.ru/cx-os/cx-os:base

USER nobody
COPY --from=build-env --chown=nobody:nobody                  /perses /perses
COPY --from=build-env --chown=nobody:nobody /go/bin/perses       /bin/
COPY --from=build-env --chown=nobody:nobody /go/bin/percli       /bin/
COPY --chown=nobody:nobody LICENSE                           /LICENSE
COPY --chown=nobody:nobody cue/schemas/                      /etc/perses/cue/schemas/
COPY --chown=nobody:nobody cue.mod/                          /etc/perses/cue.mod/
COPY --chown=nobody:nobody docs/examples/config.docker.yaml  /etc/perses/config.yaml

WORKDIR /perses

EXPOSE     8080
VOLUME     ["/perses"]
ENTRYPOINT [ "/bin/perses" ]
CMD        ["--config=/etc/perses/config.yaml", \
            "--log.level=error"]
