FROM docker.cldx.io/golang:1.23-bookworm  AS build-env
RUN apt update && apt install -y mailcap wget make
COPY . .
RUN make build-cli

FROM hbr-1.int.ops.cldx.ru/cx-os/cx-os:base-curl
RUN apt update && apt install  --no-install-recommends --no-install-suggests -y make git && \
    apt-get remove --purge --auto-remove -y && \
    rm -rf /var/lib/apt/lists/*
RUN mkdir /perses
COPY --from=build-env  /go/bin/percli       /bin/
WORKDIR /perses